version: '3'

networks:
  net1:
    driver: bridge

services:
  web:
    image: adonis:latest
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks:
      net1:
        aliases:
          - server
    volumes: 
      - ./:/app
    depends_on:
      - postgres
      
  postgres:
    image: postgres:9.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD:${DB_PASSWORD}
    networks:
      net1:
        aliases:
          - postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
