version: '3'

services:
  web:
    image: adonis:latest
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes: 
      - ./:/app
    # depends_on:
    #   - postgres
      
  # postgres:
  #   image: postgres:9.6
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   environment:
  #     - POSTGRES_PASSWORD:${DB_PASSWORD}
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
